"""empty message

Revision ID: 475da0e7d80e
Revises: 2cb88c3be376
Create Date: 2022-01-17 04:47:31.339189-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475da0e7d80e'
down_revision = '2cb88c3be376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('image_id', sa.Integer(), nullable=True))
    op.add_column('category', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'category', 'image', ['image_id'], ['id'])
    op.add_column('file', sa.Column('post_id', sa.Integer(), nullable=True))
    op.add_column('file', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'file', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'file', 'user', ['user_id'], ['id'])
    op.add_column('post', sa.Column('file_id', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'file', ['file_id'], ['id'])
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'user_id')
    op.drop_column('post', 'file_id')
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_column('file', 'user_id')
    op.drop_column('file', 'post_id')
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'post_id')
    op.drop_column('category', 'image_id')
    # ### end Alembic commands ###
