"""empty message

Revision ID: 4aeadec50c4d
Revises: b167677a1e4c
Create Date: 2022-01-17 06:14:42.093245-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aeadec50c4d'
down_revision = 'b167677a1e4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_file_id_fkey', 'post', type_='foreignkey')
    op.drop_column('post', 'file_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('post_file_id_fkey', 'post', 'file', ['file_id'], ['id'])
    # ### end Alembic commands ###
