"""empty message

Revision ID: 527b3af5cf2f
Revises: d99f8baa0b0b
Create Date: 2022-01-17 05:26:15.890452-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527b3af5cf2f'
down_revision = 'd99f8baa0b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_image_id_fkey', 'category', type_='foreignkey')
    op.drop_constraint('category_post_id_fkey', 'category', type_='foreignkey')
    op.drop_column('category', 'post_id')
    op.drop_column('category', 'image_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('category', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('category_post_id_fkey', 'category', 'post', ['post_id'], ['id'])
    op.create_foreign_key('category_image_id_fkey', 'category', 'image', ['image_id'], ['id'])
    # ### end Alembic commands ###
