"""empty message

Revision ID: 6d577ea1c900
Revises: 03c9197989b6
Create Date: 2022-02-01 03:21:31.610034-08:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d577ea1c900'
down_revision = '03c9197989b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('category_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('post_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'post_id')
    )
    op.add_column('category', sa.Column('image_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('category', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint(None, 'category', ['id'])
    op.create_foreign_key(None, 'category', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'category', 'image', ['image_id'], ['id'])
    op.add_column('file', sa.Column('post_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint(None, 'file', ['id'])
    op.create_foreign_key(None, 'file', 'post', ['post_id'], ['id'])
    op.create_unique_constraint(None, 'image', ['id'])
    op.add_column('post', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint(None, 'post', ['id'])
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='unique')
    op.drop_column('post', 'user_id')
    op.drop_constraint(None, 'image', type_='unique')
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_constraint(None, 'file', type_='unique')
    op.drop_column('file', 'post_id')
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_column('category', 'user_id')
    op.drop_column('category', 'image_id')
    op.drop_table('association')
    # ### end Alembic commands ###
