"""empty message

Revision ID: b167677a1e4c
Revises: 527b3af5cf2f
Create Date: 2022-01-17 05:27:32.270889-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b167677a1e4c'
down_revision = '527b3af5cf2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
