"""empty message

Revision ID: d99f8baa0b0b
Revises: 475da0e7d80e
Create Date: 2022-01-17 04:47:55.680498-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99f8baa0b0b'
down_revision = '475da0e7d80e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
