name: Deploy to AWS Lambda with S3 and Zip

env:
  S3_BUCKET_NAME: flagpost-bucket
  LAMBDA_FUNCTION_NAME: flagpost-lambda
  
on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set Up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install AWS CLI
      run: |
        sudo apt-get update && \
        sudo pip install awscli
        
    - name: Install dependencies
      run: |
        pip install -r ./backend/requirements.deploy.txt -t backend/lib
    
    - name: Create deployment package
      run: |
        cd backend/lib
        zip -r ../lambda.zip . -x "*.zip*" 
        cd ..
        zip -ru lambda.zip . -x "*.zip*" "*__pycache__*"
    
    - name: Upload deployment package to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        echo ls
        aws s3 cp backend/lambda.zip s3://${{ env.S3_BUCKET_NAME }}/lambda.zip
    
    - name: Deploy to AWS Lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        LAMBDA_FUNCTION_NAME: ${{ env.LAMBDA_FUNCTION_NAME }}
      run: |
        aws lambda update-function-code \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --s3-bucket ${{ env.S3_BUCKET_NAME }} \
          --s3-key lambda.zip
