#name: Zappa Django deployement
#
#on:
#  push:
#    branches:
#      - 'dev'
#
#jobs:
#  deploy-django-serverless:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up Python 3.8
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.8
#
#      - name: Setting up AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: us-east-1
#
#      - name: Create virtual env
#        run: |
#          python -m pip install --upgrade pip
#          pip install virtualenv
#          python -m virtualenv env
#
#      - name: Install Requirements
#        run: |
#          . env/bin/activate
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
#          deactivate
#
#      - name: Update Django application using zappa
#        run: |
#          . env/bin/activate
#          pip install setuptools==57.0.0
#          zappa update dev
#          zappa manage dev migrate
#
#      - name: Create Django application using zappa
#        if: ${{ failure() }}
##        if: failure() && steps.updateDjangoApplicationUsingZappa.outcome == 'failure'
#        run: |
#          . env/bin/activate
#          zappa tail dev --filter "ERROR"
##          zappa deploy dev
##          zappa manage dev migrate