name: Deploy to AWS Lambda with S3 and Zip

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install AWS CLI
      run: |
        sudo apt-get update && \
        sudo apt-get -y install python3-pip && \
        sudo pip3 install awscli
        
    - name: Install dependencies
      run: pip3 install -r ./backend/requirements.txt -t ./backend
    
    - name: Create deployment package
      run: |
        cd backend
        rm -f lambda.zip
        zip -r lambda.zip . -x "*.git*" "*.zip*" "*__pycache__*"
    
    - name: Upload deployment package to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp lambda.zip s3://${{ secrets.S3_BUCKET_NAME }}/lambda.zip
    
    - name: Deploy to AWS Lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        LAMBDA_FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_NAME }}
        
      run: |
        aws lambda update-function-code \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --s3-bucket ${{ secrets.S3_BUCKET_NAME }} \
          --s3-key lambda.zip
